# Generated by Django 5.0.3 on 2024-04-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_company_users_delete_movie_company_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='conact',
            new_name='contact',
        ),
    ]
