# Generated by Django 5.0.3 on 2024-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_conact_candidate_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobtype',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
