# Generated by Django 5.0.3 on 2024-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidate_country_candidate_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdescription', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibiltiy', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('companywebsite', models.CharField(max_length=250)),
                ('companyemail', models.CharField(max_length=20)),
                ('companycontact', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
