# Generated by Django 5.0.3 on 2024-04-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDetails',
            new_name='JobDetail',
        ),
    ]
