# Generated by Django 5.0.3 on 2024-04-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_responsibiltiy_jobdetail_responsibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='user_id',
            new_name='company_id',
        ),
    ]
