# Generated by Django 5.0.3 on 2024-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
